package com.cs65.homie.models;

import java.sql.Timestamp;
import java.util.Date;

public class Message {
    // message id - generated by firebase
    private String mid;
    private String text;
    private long timestamp;
    private String senderId;
    private String receiverId;

    public Message() {
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    // these funcs with underscore: for easier rdb access
    public Date _getDatetime() {
        return new Timestamp(timestamp);
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public void setDatetime(Date timestamp) {
        this.timestamp = timestamp.getTime();
    }

    public String getSenderId() {
        return senderId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    public boolean _isValid() {
        return senderId != null && receiverId != null && text != null && timestamp != 0;
    }

    public String _getPairId() {
        return (senderId != null && receiverId != null) ? senderId.compareTo(receiverId) < 0 ? senderId + receiverId : receiverId + senderId : null;
    }

    public String getMid() {
        return mid;
    }

    public void setMid(String mid) {
        this.mid = mid;
    }
}
